// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYTgY2bNILAbFsJez8YUfO0IM-Qm_katE',
    appId: '1:814565265259:web:451f46a1e054a83bba462e',
    messagingSenderId: '814565265259',
    projectId: 'fine-booking-470814-n8',
    authDomain: 'fine-booking-470814-n8.firebaseapp.com',
    storageBucket: 'fine-booking-470814-n8.firebasestorage.app',
    measurementId: 'G-PYC2DF9LY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0Tojr7tn2uQ0ZJH2t1mMDnLHei7yCrU',
    appId: '1:814565265259:android:a40c42b161726914ba462e',
    messagingSenderId: '814565265259',
    projectId: 'fine-booking-470814-n8',
    storageBucket: 'fine-booking-470814-n8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqwOF3yDhn04HnQ4Gun2dNbjo2vO-pZa0',
    appId: '1:814565265259:ios:650376cd315a534cba462e',
    messagingSenderId: '814565265259',
    projectId: 'fine-booking-470814-n8',
    storageBucket: 'fine-booking-470814-n8.firebasestorage.app',
    iosBundleId: 'com.example.hitrateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqwOF3yDhn04HnQ4Gun2dNbjo2vO-pZa0',
    appId: '1:814565265259:ios:650376cd315a534cba462e',
    messagingSenderId: '814565265259',
    projectId: 'fine-booking-470814-n8',
    storageBucket: 'fine-booking-470814-n8.firebasestorage.app',
    iosBundleId: 'com.example.hitrateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYTgY2bNILAbFsJez8YUfO0IM-Qm_katE',
    appId: '1:814565265259:web:eef7d7ae9d7a4583ba462e',
    messagingSenderId: '814565265259',
    projectId: 'fine-booking-470814-n8',
    authDomain: 'fine-booking-470814-n8.firebaseapp.com',
    storageBucket: 'fine-booking-470814-n8.firebasestorage.app',
    measurementId: 'G-DQSFT2N18E',
  );
}
